### ISSUE TITLE
Tracking Issue and API Proposal for wgpu on "Downlevel" APIs and Hardware

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1244]
# Definitions

**Downlevel**: An API or piece of hardware that does not support the feature level required to allow full webgpu API usage. Originally used for DX11's support for DX9 and DX10 hardware, now used in the context of wgpu.
**Platform**: A combination of the hardware, API, and driver in use. These come together to create the features available to the user.

# Intro

We all agree that we want wgpu to eventually be able to run on basically any hardware we throw at it. This means we will add support for APIs and hardware that cannot offer the full webgpu ~~experience~~ spec. When running on such APIs or devices, wgpu needs to be able to throw validation errors when the user uses more features than the backend supports, avoiding potential UB in the backend. In addition, this information should be provided to the user so they can smoothly fall back to implementations that don't use the unsupported features, or smoothly exit if they have no fallback path.

This issue contains two sections. First an API proposal on how this should be exposed to the user, then a list of downlevel platforms that are considered valuable to support.

# API Proposal

wgpu as an API should assume that the backend is fully featured by default. These efforts are for the people who want to go out of their way to support older platform. As such, the proposed API will not require the user to enable features, all features and limits available will be used to their maximum values.

This API will parallel the Features/Limits API, adding a DownlevelFeatures and DownlevelLimits bitflags and struct.

Two methods would be added:

```rust
fn Adapter::webgpu_compatability(&self) -> Compatibility;
fn Device::webgpu_compatability(&self) -> Compatibility;
```

The `Compatability` struct would be defined as the following.

```rust
pub struct Compatibility {
    pub features: DownlevelFeatures,
    pub limits: DownlevelLimits,
}

impl Compatibility {
    pub fn is_conformant(&self) -> bool,
}
```

When targeting WebGPU through wasm, this would always return "Conformant".

To give an example of things that would be in the feature and limits struct, here are some possibilities.

```rust
bitflags! {
    pub struct DownlevelFeatures: u128 {
        // FL10 and below hardware (and webgl) doesn't necessarily support compute.
        const COMPUTE_SHADERS = 0x0000_0000_0000_0001; 
		// SM2 hardware doesn't support non-constant control flow.
        const NON_CONSTANT_CONTROL_FLOW = 0x0000_0000_0000_0002;
    }
}

pub struct DownlevelLimits: u128 {
	// DX11 limits UAV + RTV to 8, DX11_1 to 64.
	pub maximum_writable_storage_buffers_and_storage_images_and_render_targets: u32,
}
```

These will also need to be threaded through gfx-hal.

The exact names, API shape, and how things are grouped is, as always, up to bikeshedding. I wanted to start the conversation.

# Targets

This is an incomplete and non-prioritized list to track all potential downlevel targets as well as collect relevant issues. The checkmarks indicate we _can_ run on them if a limited program is run on it. If checks are missing, please add them.

- [x] DX11 (gfx tracking issue https://github.com/gfx-rs/gfx/issues/3421)
  - [x] FL11_1 (FL11_1 _might_ not be downlevel, needs investigation)
  - [x] FL11_0
  - [x] FL10_1
  - [x] FL10_0 (https://github.com/gfx-rs/gfx/pull/3660)
  - [ ] FL9_3
  - [ ] FL9_2
  - [ ] FL9_1
- [ ] WebGL
  - [ ] WebGL2
  - [ ] WebGL (might not be usable)
- [ ] Desktop GL
  - [ ] GL4.5
  - [ ] GL4.2
  - [ ] GL3.3
  - [ ] GL2.1
- [ ] GLES
  - [ ] GLES3.2
  - [ ] GLES3.1
  - [ ] GLES3.0
  - [ ] GLES2.1
  - [ ] GLES2.0

Notable exclusions: GLES1 is fixed function only and is incompatible with modern shading. I only included commonly used versions of GL that are often targeted for compatibility reasons so the list wouldn't be terribly long.

**Comment by cwfitzgerald** [comment]
Closing this as our downlevel situation has improved and we now have good support for GLES under the new hal.
