### ISSUE TITLE
[meta] GLES3 backend restrictions

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1574]
This is spawned from #1510. We are trying to express all the additional restrictions in `wgt::DownlevelCapabilities`, but some things we don't know how to express, yet. So this issue is meant to track them.

- [ ] each texture is only allowed to be used with at most one sampler (combined) in all the shaders making a pipeline.
- [ ] unable to select mipmap levels and array layers for the views of sampled textures
    - we can modify the texture state to limit the mipmap levels, but this would affect all the views into this texture at once
    - the array layer restrictions could possibly be implemented on the shader side, but this is work
- [ ] unable to interpret 2D array texture as cubes.
    - currently we detect if it *can be* a cube map, and make it a cube map. This is a hack we deserve, but not the one we need.
- [ ] base instance is not supported
    - API side is fixed by re-binding the instance-rate buffers with different offsets
    - shader side needs #1573
- [x] base vertex is not supported
    - exposed as `wgt::DownlevelFlags::BASE_VERTEX`
    - perhaps, we can still work around it in a way similar to base instance?
