### ISSUE TITLE
Further spec compliance

### ISSUE THREAD

**Issue by crowlKats** [gfx-rs/wgpu#2170]
- [x] introduce the `DEPTH_CLIP_CONTROL` feature (edit: #2171)
- [x] introduce the `INDIRECT_FIRST_INSTANCE` feature (edit: #2206)
- [x] implement `GPUCommandEncoder::fillBuffer`
- [x] `GPURenderPassDescriptor::colorAttachments` is now a list of optional elements (edit: #2778)
- [x] `GPURenderPassLayout::colorFormats` is now a list of optional elements (edit: #2778)
- [x] `GPUFragmentState::targets` is now a list of optional elements (edit: #2778)
- [x] `GPUPipelineDescriptorBase::layout` now accepts an enum as well as the `GPUPipelineLayout` (#2895)
- [x] remove `GPURenderPassEncoder::writeTimestamp` and `GPUComputePassEncoder::writeTimestamp` in favour of Descriptor properties
- [x] `GPURenderPassEncoder::beginOcclusionQuery` missing
- [x] `GPURenderPassEncoder::endOcclusionQuery` missing
- [x] `GPURenderPassDescriptor::occlusionQuerySet` missing
- [x] `GPUTextureDescriptor::viewFormats` missing (#3237)
- [ ] `GPURenderPassDescriptor::maxDrawCount` missing: https://github.com/gfx-rs/wgpu/issues/8737
- [x] `GPURenderBundleEncoder::drawIndexedIndirect` missing
- [ ] #8831
- [x] `GPUShaderModule::getCompilationInfo` missing
- [x] `GPURenderPassColorAttachment::depthSlice` missing: https://github.com/gfx-rs/wgpu/issues/4764
- [ ] `AdapterInfo::architecture` missing: https://github.com/gfx-rs/wgpu/issues/8649
- [ ] `GPUDeviceDescriptor::defaultQueue` missing: https://github.com/gfx-rs/wgpu/issues/4014
- [x] `GPUMipmapFilterMode` missing
- [ ] `GPUDepthStencilState` `depthWriteEnabled` and `depthCompare` should be optional: https://github.com/gfx-rs/wgpu/issues/8830
- [ ] `setBindGroup`'s `bindGroup` argument should be optional: https://github.com/gfx-rs/wgpu/issues/4738
- [ ] `setVertexBuffer`'s `buffer` argument should be optional: https://github.com/gfx-rs/wgpu/issues/7354
- [x] limit `maxBindingsPerBindGroup` missing (https://github.com/gfx-rs/wgpu/pull/2957)
- [x] limit `maxColorAttachments` missing (https://github.com/gfx-rs/wgpu/pull/5218)
- [x] limit `maxColorAttachmentBytesPerSample` missing (https://github.com/gfx-rs/wgpu/pull/5218)
- [ ] #8832
- [ ] limit `maxInterStageShaderVariables` missing: https://github.com/gfx-rs/wgpu/issues/5577
- [x] feature `rg11b10ufloat-renderable` missing (https://github.com/gfx-rs/wgpu/pull/3701)
- [x] feature `bgra8unorm-storage` missing (https://github.com/gfx-rs/wgpu/pull/4228)
- [x] feature `float32-filterable` missing (https://github.com/gfx-rs/wgpu/pull/4759)
- [x] implement `WGSLLanguageFeatures` (github.com/gfx-rs/wgpu/pull/6814)
- [x] TextureFormat `rgb10a2uint` missing (https://github.com/gfx-rs/wgpu/pull/4199)
- [x] VertexFormat `unorm10-10-10-2` missing (https://github.com/gfx-rs/wgpu/pull/5477)

JS Only:
- [x] js-only: implement `GPUPipelineError`
- [x] js-only: implement `GPUInternalError`

**Comment by kvark** [comment]
Thank you for taking a stab at this!
We actually don't need this new `fill_buffer` method in wgpu-hal, there is already `clear_buffer` for exactly the same purpose. The API difference between them is the `value: u8`, but if you look at WebGPU spec, there isn't a value there either (because it would be more difficult to implement) - https://gpuweb.github.io/gpuweb/

So all that needs to be done here is exposing the method to wgpu-rs

**Comment by PJB3005** [comment]
#3701 added `RG11B10UFLOAT_RENDERABLE`, so that can be ticked off.

**Comment by inner-daemons** [comment]
Any updates to this?

**Comment by crowlKats** [comment]
@inner-daemons spec compliance gets constantly worked on, however this list hasnt been updated for quite a while and is long out of date.

maybe at this point, given that most of these are completed or have their dedicated issue, it would make sense to close.
thoughts @andyleiserson ?

**Comment by andyleiserson** [comment]
I went through the description and made sure that everything is either done or tracked by a dedicated issue, so I think we can close this.

We could do some additional grooming of issue labels to make it easier to search for spec conformance issues. Right now I expect there are conformance issues in all of `area: api`, `area: correctness`, and `area: validation`, which seems okay, but it might be useful to be able to distinguish which of those are related to standardized functionality and which are related to experimental APIs or wgpu extensions.

**Comment by inner-daemons** [comment]
@andyleiserson FYI, there used to be the WebGPU spec v1 milestone which can probably be used to filter many WebGPU compliance related issues. This issue has that milestone.
