### ISSUE TITLE
Web Platform Tracking Issue

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#3674]
Compiling to the web is becoming an increasingly important target. This issue serves as a tracking issue for improvements and issues on the Web platform. Both WebGL and WebGPU.

### General
- [x] https://github.com/gfx-rs/wgpu/issues/2804
- Multithreading on WASM
  - [x]  https://github.com/gfx-rs/wgpu/issues/2884
  - [x] https://github.com/gfx-rs/wgpu/issues/2652
- [x] https://github.com/gfx-rs/wgpu/issues/4593

### WebGPU
- [x]  https://github.com/gfx-rs/wgpu/issues/3299
- [ ] https://github.com/gfx-rs/wgpu/issues/3675
- [ ] https://github.com/gfx-rs/wgpu/issues/3677
- [x] https://github.com/gfx-rs/wgpu/issues/3684

### WebGL
- [ ]  https://github.com/gfx-rs/wgpu/issues/4276
- [ ]  https://github.com/gfx-rs/wgpu/issues/1614
- [ ]  https://github.com/gfx-rs/wgpu/issues/2117
- [ ]  https://github.com/gfx-rs/wgpu/issues/2343
- [ ]  https://github.com/gfx-rs/wgpu/issues/3583
- [x]  https://github.com/gfx-rs/wgpu/issues/3349
- [x]  https://github.com/gfx-rs/wgpu/issues/3375
- [ ]  https://github.com/gfx-rs/wgpu/issues/3644
- [ ]  https://github.com/gfx-rs/wgpu/issues/4371
- [ ] https://github.com/gfx-rs/wgpu/issues/3679
- [ ] https://github.com/gfx-rs/wgpu/issues/3161
- [ ] https://github.com/gfx-rs/wgpu/issues/7370
- [x] https://github.com/gfx-rs/wgpu/issues/7361
