### ISSUE TITLE
[meta] Gecko integration tracking

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#374]
This is a tracker for ecosystem issues associated with integrating `wgpu` into Gecko. It doesn't include issues within Gecko codebase. See https://phabricator.services.mozilla.com/D49458

## Architecture

- [x] IPC: https://github.com/gfx-rs/wgpu/issues/146
- [x] multi-client: https://github.com/gfx-rs/wgpu/issues/354

## CI breakage

Linux:
  - [x] https://github.com/gfx-rs/wgpu/pull/371

macOS:
  - [ ] https://github.com/SSheldon/rust-objc-exception/pull/5
  - [x] https://github.com/gfx-rs/gfx/pull/3047

Windows:
  - [x] https://github.com/grovesNL/spirv_cross/pull/116
  - [x] https://github.com/gfx-rs/gfx/pull/3069
  - [x] https://github.com/gfx-rs/gfx/pull/3076
  - [x] https://github.com/alexcrichton/cc-rs/pull/455

Android:
  - [x] https://github.com/KhronosGroup/SPIRV-Cross/pull/1193

## Dependency bloat

SPIRV-Cross tests: https://github.com/gfx-rs/SPIRV-Cross-Minimal

- [x] `arrayvec-0.4` removal:
  - [x] https://github.com/crossbeam-rs/crossbeam/issues/446
  - [x] https://github.com/oconnor663/blake2_simd/issues/16
  - [x] https://github.com/servo/uluru/pull/11

**Comment by kvark** [comment]
This happened :tada:
