### ISSUE TITLE
[meta] Vulkan tutorial shaders validation

### ISSUE THREAD

**Issue by Gordon-F** [gfx-rs/wgpu#4336]
All issues founded after run gfx-rs/naga#885.

- [ ] [mrt.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/deferredshadows/mrt.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/deferredshadows/mrt.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(58)', bin/naga.rs:116:64
```

- [ ] [deferred.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/deferredshadows/deferred.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/deferredshadows/deferred.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(225)', bin/naga.rs:116:64
```

- [ ] [geom.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/deferredshadows/geom.spv)
```rust
Convert: Vulkan/data/shaders/glsl/deferredshadows/geom.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedExecutionModel(3)', bin/naga.rs:116:64
```

- [ ] [mrt.vert.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/deferredshadows/mrt.vert.spv)
```rust
Convert: Vulkan/data/shaders/glsl/deferredshadows/mrt.vert.spv
standard function 'Inverse' is not implemented yet:
```

- [ ] [scene.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/rayquery/scene.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/rayquery/scene.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownCapability(4472)', bin/naga.rs:116:64
```

- [ ] [base.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/tessellation/base.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/tessellation/base.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(25)', bin/naga.rs:116:64
```

- [ ] [passthrough.tesc.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/tessellation/passthrough.tesc.spv)
```rust
Convert: Vulkan/data/shaders/glsl/tessellation/passthrough.tesc.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedExecutionModel(1)', bin/naga.rs:116:64
```

- [ ] [passthrough.tese.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/tessellation/passthrough.tese.spv)
```rust
Convert: Vulkan/data/shaders/glsl/tessellation/passthrough.tese.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedExecutionModel(2)', bin/naga.rs:116:64
```

- [ ] [reflect.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/texturecubemaparray/reflect.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/texturecubemaparray/reflect.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(54)', bin/naga.rs:116:64
```

- [ ] [skybox.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/texturecubemaparray/skybox.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/texturecubemaparray/skybox.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(14)', bin/naga.rs:116:64
```

- [ ] [closesthit.rchit.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/raytracingreflections/closesthit.rchit.spv)
```rust
Convert: Vulkan/data/shaders/glsl/raytracingreflections/closesthit.rchit.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownCapability(4479)', bin/naga.rs:116:64
```

- [ ] [base.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/displacement/base.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/displacement/base.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(24)', bin/naga.rs:116:64
```

- [ ] [sparseresidency.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/texturesparseresidency/sparseresidency.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/texturesparseresidency/sparseresidency.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedInstruction(Function, ImageSparseSampleImplicitLod)', bin/naga.rs:116:64
```

- [ ] [composition.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/subpasses/composition.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/subpasses/composition.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedImageDim(6)', bin/naga.rs:116:64
```

- [ ] [postprocess.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/debugmarker/postprocess.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/debugmarker/postprocess.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(57)', bin/naga.rs:116:64
```

- [ ] [particle.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/computenbody/particle.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/computenbody/particle.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedBuiltIn(16)', bin/naga.rs:116:64
```

- [ ] [particle_calculate.comp.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/computenbody/particle_calculate.comp.spv)
```rust
Convert: Vulkan/data/shaders/glsl/computenbody/particle_calculate.comp.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedInstruction(Function, MemoryBarrier)', bin/naga.rs:116:64
```

- [ ] [pbrtexture.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/pbrtexture/pbrtexture.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/pbrtexture/pbrtexture.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(394)', bin/naga.rs:116:64
```

- [ ] [irradiancecube.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/pbrtexture/irradiancecube.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/pbrtexture/irradiancecube.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(76)', bin/naga.rs:116:64
```

- [ ] [skybox.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/pbrtexture/skybox.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/pbrtexture/skybox.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(69)', bin/naga.rs:116:64
```

- [ ] [prefilterenvmap.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/pbrtexture/prefilterenvmap.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/pbrtexture/prefilterenvmap.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(249)', bin/naga.rs:116:64
```

- [ ] [descriptorindexing.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/descriptorindexing/descriptorindexing.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/descriptorindexing/descriptorindexing.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedExtension("SPV_EXT_descriptor_indexing")', bin/naga.rs:116:64
```

- [ ] [parallax.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/parallaxmapping/parallax.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/parallaxmapping/parallax.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(239)', bin/naga.rs:116:64
```

- [ ] [textoverlay.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/base/textoverlay.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/base/textoverlay.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(13)', bin/naga.rs:116:64
```

- [ ] [uioverlay.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/base/uioverlay.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/base/uioverlay.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(17)', bin/naga.rs:116:64
```

- [ ] [cull.comp.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/computecullandlod/cull.comp.spv)
```rust
Convert: Vulkan/data/shaders/glsl/computecullandlod/cull.comp.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedBuiltIn(24)', bin/naga.rs:116:64
```

- [ ] [uber.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/specializationconstants/uber.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/specializationconstants/uber.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(148)', bin/naga.rs:116:64
```

- [ ] [texture.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/texturemipmapgen/texture.frag.spvv)
```rust
Convert: Vulkan/data/shaders/glsl/texturemipmapgen/texture.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidAccessType(14)', bin/naga.rs:116:64
```

- [ ] [mirror.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/offscreen/mirror.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/offscreen/mirror.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(67)', bin/naga.rs:116:64
```

- [ ] [scene.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/gltfscenerendering/scene.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/gltfscenerendering/scene.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedInstruction(Type, SpecConstantFalse)', bin/naga.rs:116:64
```

- [ ] [deferred.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/deferredmultisampling/deferred.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/deferredmultisampling/deferred.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(169)', bin/naga.rs:116:64
```

- [ ] [scene.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/shadowmappingcascade/scene.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/shadowmappingcascade/scene.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedInstruction(Type, SpecConstantOp)', bin/naga.rs:116:64
```

- [ ] [geometry.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/oit/geometry.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/oit/geometry.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedStorageClass(11)', bin/naga.rs:116:64
```

- [ ] [gbuffer.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/hdr/gbuffer.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/hdr/gbuffer.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(27)', bin/naga.rs:116:64
```

- [ ] [quad.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/shadowmapping/quad.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/shadowmapping/quad.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(38)', bin/naga.rs:116:64
```

- [ ] [blur.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/ssao/blur.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/ssao/blur.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(19)', bin/naga.rs:116:64
```

- [ ] [gbuffer.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/ssao/gbuffer.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/ssao/gbuffer.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(92)', bin/naga.rs:116:64
```

- [ ] [scene.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/variablerateshading/scene.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/variablerateshading/scene.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedExtension("SPV_NV_shading_rate")', bin/naga.rs:116:64
```

- [ ] [scene.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/shadowmappingomni/scene.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/shadowmappingomni/scene.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(72)', bin/naga.rs:116:64
```

- [ ] [cubemapdisplay.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/cubemapdisplay.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/shadowmappingomni/cubemapdisplay.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(165)', bin/naga.rs:116:64
```

- [ ] [multiview.vert.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/multiview/multiview.vert.spv)
```rust
Convert: Vulkan/data/shaders/glsl/multiview/multiview.vert.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedExtension("SPV_KHR_multiview")', bin/naga.rs:116:64
```

- [ ] [viewdisplay.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/multiview/viewdisplay.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/multiview/viewdisplay.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(85)', bin/naga.rs:116:64
```

- [ ] [terrain.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/terraintessellation/terrain.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/terraintessellation/terrain.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(61)', bin/naga.rs:116:64
```

- [ ] [sem.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/sphericalenvmapping/sem.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/sphericalenvmapping/sem.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(54)', bin/naga.rs:116:64
```

- [ ] [pbribl.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/pbribl/pbribl.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/pbribl/pbribl.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(411)', bin/naga.rs:116:64
```

- [ ] [phongpass.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/radialblur/phongpass.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/radialblur/phongpass.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(43)', bin/naga.rs:116:64
```

- [ ] [radialblur.frag.spv](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/glsl/radialblur/radialblur.frag.spv)
```rust
Convert: Vulkan/data/shaders/glsl/radialblur/radialblur.frag.spv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidId(15)', bin/naga.rs:116:64
```
