### ISSUE TITLE
[meta] Constant evaluator built-in functions support

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#4507]
- [ ] `bitcast`: https://github.com/gfx-rs/wgpu/issues/7700
- [ ] `select`
- [ ] `all`
- [ ] `any`
- [ ] `quantizeToF16`

comparison

- [x] `abs`: https://github.com/gfx-rs/wgpu/pull/4879
- [x] `min`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `max`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `clamp`
- [x] `saturate`: https://github.com/gfx-rs/wgpu/pull/4879

trigonometry

- [x] `cos`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `cosh`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `sin`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `sinh`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `tan`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `tanh`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `acos`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `acosh`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `asin`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `asinh`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `atan`: https://github.com/gfx-rs/wgpu/pull/4879
- [x]  `atanh`: https://github.com/gfx-rs/wgpu/pull/4879
- [ ] `atan2`
- [x] `radians`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `degrees`: https://github.com/gfx-rs/wgpu/pull/5098

decomposition

- [x] `ceil`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `floor`: https://github.com/gfx-rs/wgpu/pull/5098
- [x]  `round`: https://github.com/gfx-rs/wgpu/pull/4879
- [x] `fract`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `trunc`: https://github.com/gfx-rs/wgpu/pull/5098
- [ ] `modf`
- [ ] `frexp` (used by CTS tests for other builtins, e.g. `sign`, as noted in #8942)
- [ ] `ldexp`

exponent

- [x] `exp`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `exp2`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `log`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `log2`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `pow`

geometry

- [ ] `dot`
- [ ] `cross`
- [ ] `distance`
- [ ] `length`
- [ ] `normalize`
- [ ] `faceForward`
- [ ] `reflect`
- [ ] `refract`

computational

- [x] `sign`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `fma`: https://github.com/gfx-rs/wgpu/pull/5098
- [ ] `mix`
- [x]  `step`: https://github.com/gfx-rs/wgpu/pull/4879
- [ ] `smoothstep`
- [x]  `sqrt`: https://github.com/gfx-rs/wgpu/pull/4879
- [x] `inverseSqrt`: https://github.com/gfx-rs/wgpu/pull/5098
- [ ] `transpose`
- [ ] `determinant`

bits

- [x] `countTrailingZeros`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `countLeadingZeros`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `countOneBits`: https://github.com/gfx-rs/wgpu/pull/5098
- [x] `reverseBits`: https://github.com/gfx-rs/wgpu/pull/5098
- [ ] `extractBits`
- [ ] `insertBits`: (has partial evaluation cases, see #9152)
- [x] `firstTrailingBit`: https://github.com/gfx-rs/wgpu/pull/5101
- [x] `firstLeadingBit`: https://github.com/gfx-rs/wgpu/pull/5101

data packing

- [ ] `pack4x8snorm`
- [ ] `pack4x8unorm`
- [ ] `pack2x16snorm`
- [ ] `pack2x16unorm`
- [ ] `pack2x16float`
- [ ] `pack4xI8`
- [ ] `pack4xU8`
- [ ] `pack4xI8Clamp`
- [ ] `pack4xU8Clamp`

data unpacking

- [ ] `unpack4x8snorm`
- [ ] `unpack4x8unorm`
- [ ] `unpack2x16snorm`
- [ ] `unpack2x16unorm`
- [ ] `unpack2x16float`
- [ ] `unpack4xI8`
- [ ] `unpack4xI8`

wgpu extensions (consider making a separate meta issue for this group if it grows)

- [ ] #8972

**Comment by ErichDonGubler** [comment]
@teoxoy: I added links to #4879 for the relevant built-ins I'm adding there, but I'm not sure if this is what you want for this tracking issue. LMK if you want me to revert.

**Comment by ErichDonGubler** [comment]
Added links for #5098.

**Comment by VlaDexa** [comment]
Data packing and unpacking gained some new functions

**Packing:**
- pack4xI8
- pack4xI8

**Unpacking:**
- unpack4xI8
- unpack4xI8

**Comment by ErichDonGubler** [comment]
Added the following to this list as follow-up to #6445:

- `pack4xI8`
- `pack4xU8`
- `pack4xI8Clamp`
- `pack4xU8Clamp`

**Comment by ErichDonGubler** [comment]
Added `bitcast` at https://github.com/gfx-rs/wgpu/issues/7700.

**Comment by MinerSheep** [comment]
This should be updated, in constant_evaluator.rs I'm seeing implementations for atan2, dot, cross, length, distance, normalize, and maybe more.   @andyleiserson  is it alright if I work on a few of these as well?

**Comment by andyleiserson** [comment]
@MinerSheep yes, PRs for any of the missing support are welcome. I updated the description with what I think is the current state, please point out if you see any remaining discrepancies. For anything you work on implementing, I would suggest reviewing the WebGPU spec for any corner cases with prescribed behavior, and to find and run the relevant CTS tests on your change (and then as long as the runtime is reasonable, add them to `cts_runner/test.lst` so we run them in CI). ([`docs/testing.md`](https://github.com/gfx-rs/wgpu/blob/trunk/docs/testing.md#webgpu-cts) has information on running the CTS against `wgpu`.)
