### ISSUE TITLE
Dependencies between resources prevent destroy from doing its job

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#4787]
We currently don't deallocate resources as long as their reference count (as in the counter in the `Arc` itself) does not get down to a certain number which is semantically equivalent to zero ([See the checks](https://github.com/gfx-rs/wgpu/blob/238c3732a42ca1b5eb20ca3afcb8c8f4078ee620/wgpu-core/src/track/stateless.rs#L104)).

Dependencies between resources, for example a texture view holding on to a texture, contribute a strong reference count, however we need `texture.destroy` to be able to deallocate textures even while it is referenced by texture views. This is important because the role of the `destroy` methods is to ensure resources can predictably be deallocated even in garbage collected environments (such the web).

**Comment by nical** [comment]
# TODO

 - [x] Introduce the device-global snatch guards (#4867)
 - [x] Make buffers use snatch guards (#4867)
 - [x] Make textures use snatch guards
   - [ ] make `surface_present` and `surface_texture_discard` not [mutate a texture's raw handle](https://github.com/gfx-rs/wgpu/blame/6dc9ccab8592645fda3204be1cfb5929fd7f924d/wgpu-core/src/present.rs#L343).
 - [x] accessing bind groups should happen with the snatch lock taken. 
 - [x] snatch buffers in `buffer.destroy()`
 - [x] snatch textures in `texture.destroy()`
