### ISSUE TITLE
Remove IDs and Registries

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#5121]
This is a meta issue to describe the long-ish term vision for wgpu-core's resource management and track the steps towards it.

# Registries and IDs

Internally, all wgpu-core resources are stored behind `Arc`s. Externally, they are exposed as non-clonable structs containing an ID which conceptually corresponds to a single reference to the `Arc` of a resource.

# The goal

Instead of having wgpu public types wrap a non-clonabe ID, we would like them to wrap the `Arc` to the internal resource directly (and be clonable).

# TODO

- [x] #5120
- [x] Remove remaining internal use of the IDs.
- [x] #5124
- [x] Rewrite the record-reply functionality https://github.com/gfx-rs/wgpu/issues/5974
- [ ] #8911
- [ ] (Firefox): Move the `wgpu-core` part of command recording out of the content process
- [ ] Move logic present in the `Global`'s methods into methods on wgpu-core objects
- [ ] (Firefox): Stop providing the IDs during resource creation and do ID mapping in the gecko-side bindings.
- [ ] Remove the registries

# Other Related Issues

- [ ] #8234 
- [ ] #8837

**Comment by sagudev** [comment]
> (Firefox): Stop providing the IDs during resource creation and do ID mapping in the gecko-side bindings.

How exactly would that look like? Would that be something like hashmap that would map id to Arc of wgpu object that would live in WebGPU thread?

I'm mostly asking for servo, as it would be nice to share ID mapping stuff.

**Comment by nical** [comment]
> > (Firefox): Stop providing the IDs during resource creation and do ID mapping in the gecko-side bindings.
> 
> How exactly would that look like? Would that be something like hashmap that would map id to Arc of wgpu object that would live in WebGPU thread?

Yes, that's the general idea. Depending on how you generate the IDs you could get away with arrays instead of hash maps (like wgpu-core currently does).

**Comment by sagudev** [comment]
There are some cases where this would also be useful in servo, for example when doing swapchain present we always need to send new encoder id from content process so we can create new encoder in wgpu_thread, but removing registries would allow us to have concept of wgc types that are not owned by JS (content process).

I think making descriptors generic over IDs/Arced Resources would be beneficial as that would allow servo to still reuse such types for IPC. Something like this is already done in some parts using Arc* variants descriptors: https://github.com/gfx-rs/wgpu/blob/ad194a8a3e843ef0bac1b1a7b08569cf91ac222c/wgpu-core/src/command/timestamp_writes.rs#L8-L25

**Comment by teoxoy** [comment]
Relevant to this issue: https://github.com/gfx-rs/wgpu/pull/8129#issuecomment-3233876112 (possible shape for `wgpu-core` resources, rather than the current `Snatchable` + `SnatchLock`).

**Comment by sagudev** [comment]
> Move the wgpu-core part of command recording out of the content process

This is about render bundles, right? They are currently built in content process (using IDs) and send over IPC and then resolved, but that is wrong AFAIK and will cause problem in migration. I read somewhere that this also complicates firefox as it needs to keep dom object of used resources alive while encoder is still open. I propose we go to same semantics as used by other commands/passes (at least the one that is then also used in servo; IIRC in firefox there is additional buffering of Pass command which are then unrolled on finish) so for every RenderBundleEncoder command we expose a global method that will resolve the id's and then store resolved commands (so all used resources will be kept alive by arc!).

**Comment by teoxoy** [comment]
Yeah, that item is now mainly about bundles.

> IIRC in firefox there is additional buffering of Pass command which are then unrolled on finish

We want to remove this additional buffering as well. We shouldn't need to store the commands in another Vec that on finish gets sent to the GPU process.

> so for every RenderBundleEncoder command we expose a global method that will resolve the id's and then store resolved commands

Yes this would be the ideal architecture and we should do this for pass encoders as well. IIRC doing it for passes was also necessary/blocking removal of registries but it might not be.

**Comment by teoxoy** [comment]
I think I might have some time next week to try to refactor Firefox's passes to no longer buffer in the content process.

**Comment by sagudev** [comment]
I will prepare PR with global methods for RenderBundleEncoder (but still using existing RenderBundleEncoder) just so we get "public" API ready so we can start doing internal changes.


As for the other passes it might be beneficial to still have the id and stuff in global (in servo we currently do hashmap) tho thing are complicated by &mut (we would need mutex around each renderpass).

My final goal is to have Global doing all and only remoting (for servo and firefox) other users would be able to use resources directly.

**Comment by sagudev** [comment]
> As for the other passes it might be beneficial to still have the id and stuff in global (in servo we currently do hashmap) tho thing are complicated by &mut (we would need mutex around each renderpass).

for wgpu it's nicer if we do not have this (because we would needlessly lock), but it might make stuff easier in firefox (it certainly would in servo) so I can postpone this until global is used only for remoting.

**Comment by sagudev** [comment]
> Relevant to this issue: [#8129 (comment)](https://github.com/gfx-rs/wgpu/pull/8129#issuecomment-3233876112) (possible shape for `wgpu-core` resources, rather than the current `Snatchable` + `SnatchLock`).

I do not see how we could remove `Snatchable` + `SnatchLock` for resources that can be destroyed as we still need to mutate the state.

Anyway [firstly I tried](https://github.com/sagudev/wgpu/tree/texa) to get away by using `Fallible<Texture>` everywhere, but this got involved (needs a lot of changes) so I kind give up on it (esp if we want to have `Arc<ResourceState<X>>` someday as this would be reversing many changes done here). So [next thing I tried](https://github.com/sagudev/wgpu/tree/texb) to see how hard would it be to do https://github.com/gfx-rs/wgpu/pull/8129#issuecomment-3233876112 so I tried and it got very problematic again (mind you we need to keep it snatchable). So lastly I just switched the inner field of texture (so the one that contains snatchable + raw) to now contain snatchable destructable resource (more on that in https://github.com/gfx-rs/wgpu/pull/9718). This was the nicest solution in the end and we could eventually migrate some fields to inner state I suppose.

**Comment by teoxoy** [comment]
> for wgpu it's nicer if we do not have this (because we would needlessly lock), but it might make stuff easier in firefox (it certainly would in servo) so I can postpone this until global is used only for remoting.

While that's true it's messy to have this outside of `wgpu-core`. I doubt the locking will become an issue since it won't be contended but if it does we can come up with some `cfg`s to remove the `Mutex` and have the methods take `&mut`.

**Comment by teoxoy** [comment]
> > Relevant to this issue: [#8129 (comment)](https://github.com/gfx-rs/wgpu/pull/8129#issuecomment-3233876112) (possible shape for `wgpu-core` resources, rather than the current `Snatchable` + `SnatchLock`).
> 
> I do not see how we could remove `Snatchable` + `SnatchLock` for resources that can be destroyed as we still need to mutate the state.
> 
> Anyway [firstly I tried](https://github.com/sagudev/wgpu/tree/texa) to get away by using `Fallible<Texture>` everywhere, but this got involved (needs a lot of changes) so I kind give up on it (esp if we want to have `Arc<ResourceState<X>>` someday as this would be reversing many changes done here). So [next thing I tried](https://github.com/sagudev/wgpu/tree/texb) to see how hard would it be to do [#8129 (comment)](https://github.com/gfx-rs/wgpu/pull/8129#issuecomment-3233876112) so I tried and it got very problematic again (mind you we need to keep it snatchable). So lastly I just switched the inner field of texture (so the one that contains snatchable + raw) to now contain snatchable destructable resource (more on that in [#9718](https://github.com/gfx-rs/wgpu/pull/9718)). This was the nicest solution in the end and we could eventually migrate some fields to inner state I suppose.

Yeah you are right, we would still need `Snatchable` or a `RwLock` around the inner state.

> So lastly I just switched the inner field of texture (so the one that contains snatchable + raw) to now contain snatchable destructable resource (more on that in https://github.com/gfx-rs/wgpu/pull/9718). This was the nicest solution in the end and we could eventually migrate some fields to inner state I suppose.

This sounds like the best way to move forward! Thanks for trying all the combinations to see what sticks the best :)

**Comment by sagudev** [comment]
NOTE-TO-SELF: For BGL we need both pipelines converted and PPL needs BGL converted.

**Comment by sagudev** [comment]
NOTE-TO-SELF: BG and passes depends on buffer (and other bindings) but buffer is hard (drop needs unmap but unmap needs arc https://github.com/gfx-rs/wgpu/blob/99f8284e4286c66b0515dbc5d4dea0cd432f4e6f/wgpu-core/src/resource.rs#L1004). ext-text also depends on buffer (no hardly).

**Comment by sagudev** [comment]
Here is an outline of what is still to do:

- [x] move validity of the rest (last done in https://github.com/gfx-rs/wgpu/pull/9812)
    - https://github.com/gfx-rs/wgpu/issues/9535 is similar but not strictly needed
- [x] make sure global functions are thin (they only do id mapping)
    - basically check every `impl Global` item
- [x] port render bundles to ids: https://github.com/gfx-rs/wgpu/pull/9830
- [x] port deno/wgpu to internal functions
    - #9901
    - #9950
- [x] move `Global` into separate crate (`wgpu-core-remote`)
    - in servo we would also want `wgpu-core-remote-types` which would have types and not depend on wgc to get more parallel compilation opportunities. It would need to have (or reexport from wgt) everything we need in content process (ids, idmanager, descriptors)

and then we are done. But there are still some interesting followups (I might tackle some of them):

- degeneralization of many types and various cleanups
    - https://github.com/gfx-rs/wgpu/pull/9901#issuecomment-5003425791 
- remove sync/send requirement from global (servo and ff do not need it and this will allow many simplifications)
- remove non with id methods from global for passes/bundle
    - remove non browser stuff 
- make Global as optional wrapper for instance
- always require provided id
- https://github.com/gfx-rs/wgpu/issues/8911
    - then we can do https://github.com/gfx-rs/wgpu/issues/9710
    - unmap should not raise validation errors:https://github.com/gfx-rs/wgpu/pull/9811#issuecomment-4893552826
        - should we start deferring callbacks? https://github.com/gfx-rs/wgpu/pull/9811#issuecomment-4893229163 probably not
- introduce `trait Validity: ParentDevice` and use it to implement:
```rust
resource.check_is_valid()?;
device.check_is_valid()?;
resource.same_device(device)?;
```
as we are missing some of them: https://github.com/gfx-rs/wgpu/pull/9800#discussion_r3520515945 (tho sometimes we cannot do it meaningfully: https://github.com/gfx-rs/wgpu/pull/9803/changes#r3521652872)
- remove arc layer in wgpu for core: https://github.com/gfx-rs/wgpu/blob/688e4761c993a458b5f324aa9132873f8562b728/wgpu/src/dispatch.rs#L730
- move data from wgpu's structure into underlying type (so also in it's dispatch interface trait) per idea here: https://github.com/gfx-rs/wgpu/issues/9535#issuecomment-4616746574
     - in wasm we should still cache as we do not want JS calls
- move more into internal states
- deal with tracing: https://github.com/gfx-rs/wgpu/pull/9798#discussion_r3519020136 (as we use arc to get stable address/id maybe we should make use of `Pin` and `PinnedPhantom`)
- can we avoid temp alloc just for id->arc conversion (by sizeof(Id) = sizeof(Arc) we can do it in-place)?
    - should we really accept descriptors via & as they are usually constructed on side (in wgpu core backend, deno, servo, firefox) and then we basically just clone them in core by passing them directly we could just reuse alloc of Vec and/or Arc instead of cloning
- ...

some stuff noted in https://github.com/gfx-rs/wgpu/pull/9950
- we still pass `CoreContext` to some types because of `handle_error` (which does not use self really)
- we should implement interface directly on wgpu-core resources (this will wait for other follow up work noted in #5121)
- use iterators instead of collections where methods allow

**Comment by sagudev** [comment]
We are very close here, PRs for removing `Global` from deno and wgpu are up. Last point "move Global into separate crate (wgpu-core-remote)" will be especially tricky as Ids are still used all over the place (ex: as default types for generics) and then there will be a lot of cleanups/follow ups (I will open post-#5121 metaissue for them after we close this).

**Comment by sagudev** [comment]
Markers needs to remain in wgc as they are used for tracing, but id stuff can go into wgc-remote crate.
