### ISSUE TITLE
Remove undefined behavior for ray queries

### ISSUE THREAD

**Issue by Vecvec** [gfx-rs/wgpu#6761]
**Is your feature request related to a problem? Please describe.**
Currently the ray queries have lots of undefined behavior from the spirv spec that should be removed

**Describe the solution you'd like**
Prevent the undefined behaviour

**Describe alternatives you've considered**
Not remove it.

**Additional context**
Also see #6731 for some details of what can happen.
Current known undefined behavior*:

**Vulkan**

- [x] Anytime a ray misses and `rayQueryGet*Intersection` is called - #6752 
- [x] Calling `rayQueryGetCommittedIntersection` or `rayQueryGetCandidateIntersection` when `rayQueryProceed` has not been called called on this ray query since it was initialized (or if the ray query has not been previously initialized). #8390
  - [x] Make this optional if module is trusted (This is avoidable).
- [x]  Calling `rayQueryGetCommittedIntersection` when `rayQueryProceed`'s latest return on this ray query is considered `Candidate` (and the other way round too). #8390
  - [x] Make this optional if module is trusted (This is avoidable).
- [x] Calling `rayQueryProceed` when `rayQueryInitialize` has not previously been called on this ray query. #8390
  - [x] Make this optional if module is trusted (This is avoidable).
- [x] Calling `rayQueryInitialize` with `NaN`s (or `Inf`s in origin and direction). #8390

**DX12**

- [x] Calling `rayQueryGetCommittedIntersection` or `rayQueryGetCandidateIntersection` when `rayQueryProceed` has not been called called on this ray query since it was initialized (or if the ray query has not been previously initialized). #8763 
  - [x] Make this optional if module is trusted (This is avoidable).
- [x] Calling `rayQueryGetCommittedIntersection` when `rayQueryProceed`'s latest return on this ray query is considered `Candidate` (and the other way round too). #8763 
  - [x] Make this optional if module is trusted (This is avoidable).
- [x] Calling `rayQueryProceed` when `rayQueryInitialize` has not previously been called on this ray query. #8763 
  - [x] Make this optional if module is trusted (This is avoidable).
- [x] Calling `rayQueryInitialize` with `NaN`s (or `Inf`s in origin and direction). #8763 

**Metal**
Metal's requirement's are difficult to find listed. Section 6.18.5 (Intersection Query Functions) has tables which list at which points intersection functions can be called (what happens on no intersection is not specified but many seem like they may have UB on no intersection, while others seem like they wouldn't). Additionally, behavior on an "invalid" ray (see section 2.17.2) is not specified for intersection queries but is for an intersector. Therefore, I will assume this needs similar things to the other two backends.

- [ ] Calling `rayQueryGetCommittedIntersection` or `rayQueryGetCandidateIntersection` when `rayQueryProceed` has not been called called on this ray query since it was initialized (or if the ray query has not been previously initialized).
  - [ ] Make this optional if module is trusted (This is avoidable).
- [ ] Calling `rayQueryGetCommittedIntersection` when `rayQueryProceed`'s latest return on this ray query is considered `Candidate` (and the other way round too).
  - [ ] Make this optional if module is trusted (This is avoidable).
- [ ] Calling `rayQueryProceed` when `rayQueryInitialize` has not previously been called on this ray query.
  - [ ] Make this optional if module is trusted (This is avoidable).
- [ ] Calling `rayQueryInitialize` with `NaN`s (or `Inf`s in origin and direction).
