### ISSUE TITLE
[meta] Feature Testing Checklist

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#807]
Now that we got #786, we should start taking advantage of it by introducing local "playtests".
We can take `wgpu-rs` [example matrix](https://github.com/gfx-rs/wgpu-rs/blob/d0825a219511c28bf74f8cbef9056b55fde4e04e/examples/README.md#feature-matrix) as a baseline:

- [ ] vertex attributes
- [ ] instancing
- [ ] lines and points
- [ ] sampled color textures
- [ ] storage textures
- [ ] binding array
- [ ] comparison samplers
- [ ] subresource views
- [ ] cubemaps
- [ ] multisampling
- [ ] off-screen rendering
- [ ] stencil testing
- [ ] depth testing
- [ ] depth biasing
- [ ] read-only depth
- [ ] blending
- [ ] render bundles
- [ ] compute passes
- optional extensions
- [ ] - binding indexing
- [ ] - push constants
- [ ] WGSL shaders

Note-1: we don't have to be super detailed in testing all the features in the world. It's just one of the testing layers in "defence in depth" onion of layers, above gfx-rs running on Warden and Vulkan CTS, and below wgpu-rs and WebGPU CTS. Common sense should be applied to weight the maintenance overhead versus the test coverage. I think getting a test for an entry in the feature matrix is a great start.

Note-2: it's not clear what shaders we should be using here. I suggest we start with a single shader module that outputs a full-screen quad (without vertex attributes) in VS, and writes down a solid fixed color to the output in FS. Perhaps, we can write test shaders in WGSL right away as this thing is getting more and more mature?

**Comment by DevOrc** [comment]
I'd be interested in working on this, but I was curious about a few things. 

1) Should these tests be in the player/tests directory or in a separate dedicated crate?
2) For the shaders, is WGSL ready enough to be used? I have never used it but would be wiling to learn it

If you had any other insights that would be appreciated

**Comment by kvark** [comment]
1. `player` is already a dedicated development-only crate, so it's a good place to put the tests in. More specifically, into `player/tests`
2. I don't think WGSL is ready just yet. We can go a long way with just a single SPIR-V shader that is compiled from source off-line and just fills out the screen with some color, for now.

> If you had any other insights that would be appreciated

We'd love to chat on "#wgpu:matrix.org"!

**Comment by cwfitzgerald** [comment]
Now that wgpu-rs _is_ us and we have the ability to run the CTS, I'm going to close this as a lot of these things will be covered by the CTS.
